spring:
  datasource:
      druid:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@192.168.0.200:1521:orcl
        username: xztollstation
        password: qwerty
        initial-size: 1
        max-active: 50
        max-wait: 60000
        min-idle: 5
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT * FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        max-open-prepared-statements: 20
        remove-abandoned: true
        remove-abandoned-timeout: 1800
        log-abandoned: true
  application:
    name: nsop-client
#  rabbitmq:
#    host: 192.168.0.126
#    port: 5672
#    # virtual-host: /nsop-client
#    listener:
#      simple:
#        # 采用手动应答
#        acknowledge-mode: manual
#        # 当前监听容器数
#        concurrency: 1
#        # 最大数
#        max-concurrency: 1
#        # 是否支持重试
#        retry:
#          enabled: true
#    # 支持发布确认
#    publisher-confirms: true
#    # 支持发布返回
#    publisher-returns: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mydao.nsop.client.domain.entity

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: traffic001
      client-secret: 123456789
      access-token-uri: https://traffic.qhse.cn/api/auth/oauth/token

# 自定义配置
nsop:
  traffic:
    url: https://traffic.qhse.cn/api/traffic/
    # 客户端编号
    client-num: 001
    thriftPort: 3333
  interface:
    entry: roadEntry/normal
    entry_ex: roadEntry/abnormal
    exit: roadExit/normal
    exit_ex: roadExit/abnormal
    full_quantity_black: vehicleBlack/list
    full_quantity_white: vehicleWhite/list

  ftpServer:
    download:
      ftpHost: 192.168.0.171
      ftpUserName: eykihlb
      ftpPassword: 213457023
      ftpPort: 21
      ftpPath: ""
      localPath: F:/download
    upload:
      ftpHost: 192.168.0.171
      ftpUserName: eykihlb
      ftpPassword: 213457023
      ftpPort: 22
      ftpPath: ""
      localPath: F:/download
  cmq:
    secret-id: AKIDe8OPClQB2f3D9qtSO7bqqb6MOzMVv7ap
    secret-key: A6oMgngOs8AxWqwmNmvoRpyrUryqTqKd
    endpoint-queue: https://cmq-queue-bj.api.qcloud.com
    endpoint-topic: https://cmq-topic-bj.api.qcloud.com