spring:
  application:
    name: nsop-client
  rabbitmq:
    host: 192.168.0.126
    port: 5672
    # virtual-host: /nsop-client
    listener:
      simple:
        # 采用手动应答
        acknowledge-mode: manual
        # 当前监听容器数
        concurrency: 1
        # 最大数
        max-concurrency: 1
        # 是否支持重试
        retry:
          enabled: true
    # 支持发布确认
    publisher-confirms: true
    # 支持发布返回
    publisher-returns: true


# 自定义配置
nsop:
  traffic:
    url: http://192.168.0.250:9099/
    # 客户端编号
    client-num: 001
  interface:
    entry: roadEntry/normalDriveInto
    entry_ex: roadEntry/abnormalDriveInto
    exit: roadExit/normal
    exit_ex: roadExit/abnormity

  ftpServer:
    download:
      ftpHost: 192.168.0.171
      ftpUserName: eykihlb
      ftpPassword: 213457023
      ftpPort: 21
      ftpPath: ""
      localPath: F:/download
    upload:
      ftpHost: 192.168.0.171
      ftpUserName: eykihlb
      ftpPassword: 213457023
      ftpPort: 22
      ftpPath: ""
      localPath: F:/download
  cmq:
    secret-id: AKIDe8OPClQB2f3D9qtSO7bqqb6MOzMVv7ap
    secret-key: A6oMgngOs8AxWqwmNmvoRpyrUryqTqKd
    endpoint-queue: https://cmq-queue-bj.api.qcloud.com
    endpoint-topic: https://cmq-topic-bj.api.qcloud.com